services:
  service1:
    image: ghcr.io/darkendhall/url_shortener:latest
    restart: on-failure
    depends_on:
      - db
      - consul
    ports:
      - "8080:8080"
    networks:
      - url-shortener
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/short" ]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    environment:
      CONSUL_HOST: consul

  service2:
    image: ghcr.io/darkendhall/url_shortener:latest
    restart: on-failure
    depends_on:
      - db
      - consul
    ports:
      - "8081:8080"
    networks:
      - url-shortener
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/short" ]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    environment:
      CONSUL_HOST: consul

  service3:
    image: ghcr.io/darkendhall/url_shortener:latest
    restart: on-failure
    depends_on:
      - db
      - consul
    ports:
      - "8082:8080"
    networks:
      - url-shortener
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8082/short" ]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    environment:
      CONSUL_HOST: consul

  db:
    image: mysql:8.0.27
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    networks:
      - url-shortener

  consul:
    image: consul:1.12.0
    ports:
      - "8500:8500"
      - "8600:8600"
    networks:
      - url-shortener
    environment:
      CONSUL_LOCAL_CONFIG:
        '{
          "server": true,
          "ui_config": {
            "enabled": true
          },
          "log_level": "INFO",
          "node_name": "server-1",
          "bootstrap_expect": 1,
          "autopilot": {
            "cleanup_dead_servers": true,
            "last_contact_threshold": "200ms",
            "server_stabilization_time": "10s"
          },
          "acl": {
            "enabled": true,
            "default_policy": "deny",
            "enable_token_persistence": true,
            "tokens": {
              "initial_management": "0e2bafa8-d534-34ec-5a2a-20239ee6eb8b",
              "agent": "0e2bafa8-d534-34ec-5a2a-20239ee6eb8b"
            }
          }
        }'


volumes:
  mysql-data: { }
  consul-data: { }

networks:
  url-shortener: { }
