services:
  service1:
    image: ghcr.io/darkendhall/url_shortener:latest
    restart: on-failure
    depends_on:
      - db
      - consul
    ports:
      - "8080:8080"
    networks:
      - url-shortener
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/short" ]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    environment:
      CONSUL_HOST: consul

  service2:
    image: ghcr.io/darkendhall/url_shortener:latest
    restart: on-failure
    depends_on:
      - db
      - consul
    ports:
      - "8081:8080"
    networks:
      - url-shortener
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/short" ]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    environment:
      CONSUL_HOST: consul

  service3:
    image: ghcr.io/darkendhall/url_shortener:latest
    restart: on-failure
    depends_on:
      - db
      - consul
    ports:
      - "8082:8080"
    networks:
      - url-shortener
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8082/short" ]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    environment:
      CONSUL_HOST: consul

  db:
    image: mysql:8.0.27
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    networks:
      - url-shortener

  consul:
    image: consul:1.12.0
    ports:
      - "8500:8500"
      - "8600:8600"
    networks:
      - url-shortener
      - consul-network
    environment:
      CONSUL_LOCAL_CONFIG:
        '{
          "server": true,
          "ui_config": {
            "enabled": true
          },
          "node_name": "server-1",
          "bootstrap_expect": 1,
          "autopilot": {
            "cleanup_dead_servers": true,
            "last_contact_threshold": "200ms",
            "server_stabilization_time": "10s"
          },
          "acl": {
            "enabled": true,
            "default_policy": "deny",
            "enable_token_persistence": true,
            "tokens": {
              "initial_management": "0e2bafa8-d534-34ec-5a2a-20239ee6eb8b",
              "agent": "0e2bafa8-d534-34ec-5a2a-20239ee6eb8b"
            }
          }
        }'

  vault:
    image: vault:1.10.3
    ports:
      - "8200:8200"
    networks:
      - url-shortener
      - consul-network
    command: [ 'server', 'exec vault secrets enable consul',
               'exec vault write consul/config/access address="consul:8500" token="0e2bafa8-d534-34ec-5a2a-20239ee6eb8b"',
               'exec vault write consul/roles/my-role consul_roles="api-server"' ]
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_LOCAL_CONFIG:
        '{
        	"listener": [{
         		"tcp": {
         			"address": "vault:8200",
         			"tls_disable": 1
         		}
         	}],
         	"storage": {
         		"consul": {
         			"address": "consul:8500",
         			"path": "vault"
         		}
         	},
         	"service_registration": {
         		"consul": {
         			"address": "consul:8500"
         		}
         	},
         	"ui":true
         }'
      VAULT_ADDR: "http://vault:8200"

volumes:
  mysql-data: { }
  consul-data: { }

networks:
  url-shortener: { }
  consul-network: { }
