version: "3.8"
services:
  service1:
    image: ghcr.io/darkendhall/url_shortener:latest
    restart: unless-stopped
    depends_on:
      - consul
      - db
      - consul-config-url_shortener
    ports:
      - "8081:8080"
    networks:
      - service-discovery
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://service1:8080/health" ]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    environment:
      CONSUL_HOST: consul

  service2:
    image: ghcr.io/darkendhall/url_shortener:latest
    restart: unless-stopped
    depends_on:
      - consul
      - db
      - consul-config-url_shortener
    ports:
      - "8082:8080"
    networks:
      - service-discovery
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://service2:8081/health" ]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    environment:
      CONSUL_HOST: consul

  service3:
    image: ghcr.io/darkendhall/url_shortener:latest
    restart: unless-stopped
    depends_on:
      - consul
      - db
      - consul-config-url_shortener
    ports:
      - "8083:8080"
    networks:
      - service-discovery
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://service3:8082/health" ]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    environment:
      CONSUL_HOST: consul

  db:
    image: mysql:8.0.27
    restart: unless-stopped
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/data/application/init.sql
    command: --init-file /data/application/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: password
    networks:
      - service-discovery

  consul:
    restart: unless-stopped
    image: consul:1.12.0
    ports:
      - "8500:8500"
      - "8600:8600"
    networks:
      - service-discovery
      - consul-config
    environment:
      CONSUL_LOCAL_CONFIG:
        '{
          "server": true,
          "ui_config": {
            "enabled": true
          },
          "log_level": "INFO",
          "node_name": "server-1",
          "bootstrap_expect": 1,
          "autopilot": {
            "cleanup_dead_servers": true,
            "last_contact_threshold": "200ms",
            "server_stabilization_time": "10s"
          },
          "dns_config": {
                "enable_truncate": true
              }
        }'

  consul-config-url_shortener:
    depends_on:
      - consul
    image: consul:1.12.0
    command: "kv import -http-addr=consul:8500 @/url-shortener.json"
    volumes:
      - type: bind
        source: ./consul-config/url-shortener.json
        target: /url-shortener.json
    networks:
      - consul-config

  consul-config-auth:
    depends_on:
      - consul
    image: consul:1.12.0
    command: "kv import -http-addr=consul:8500 @/auth.json"
    volumes:
      - type: bind
        source: ./consul-config/auth.json
        target: /auth.json
    networks:
      - consul-config

  nginxplus:
    restart: unless-stopped
    build: ./nginxplus
    ports:
      - "80:8080"
    volumes:
      - nginx:/etc/nginx
      - type: bind
        source: ./nginxplus/nginx.conf
        target: /etc/nginx/conf.d/load-balancer.conf
    networks:
      - service-discovery

  auth:
    depends_on:
      - consul
      - consul-config-auth
      - rabbit
    image: ghcr.io/fredrik-philippe-vimbayi/auth-microservice:v1.4.0
    ports:
      - "8084:8080"
    networks:
      - service-discovery
      - rabbitmq

  rabbit:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - rabbitmq

volumes:
  mysql-data: { }
  consul-data: { }
  nginx: { }

networks:
  consul-config: { }
  service-discovery: { }
  rabbitmq: { }
