name: Create and publish a Docker image (Micronaut)

on:
  release:
    branches:
      - quarkus
    types: [ created ]

env:
  REGISTRY: ghcr.io
  ACTOR: ${{github.actor}}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package -Pnative --define quarkus.container-image.build=true --define quarkus.native.container-build=true --file pom.xml

      - name: Log in to the Container registry
        uses: docker/login-action@dd4fa0671be5250ee6f50aedf4cb05514abda2c7
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.ACTOR }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push docker image
        run: docker push ghcr.io/darkendhall/url_shortener:quarkus
