name: Create and publish a Docker image (Micronaut)

on:
  release:
    branches:
      - micronaut
    types: [ created ]

env:
  REGISTRY: ghcr.io
  ACTOR: ${{github.actor}}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package -Dpackaging=docker-native -Pgraalvm --file pom.xml

      - name: Log in to the Container registry
        uses: docker/login-action@dd4fa0671be5250ee6f50aedf4cb05514abda2c7
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.ACTOR }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag Docker image(Micronaut)
        run: docker image tag url_shortener ghcr.io/darkendhall/url_shortener:micronaut

      - name: Tag Docker image(latest)
        run: docker image tag url_shortener ghcr.io/darkendhall/url_shortener:latest

      - name: Push Docker image(Micronaut)
        run: docker push ghcr.io/darkendhall/url_shortener:micronaut

      - name: Push Docker image(latest)
        run: docker push ghcr.io/darkendhall/url_shortener:latest
